volumes:
  pgdata:
  redis_data:
  static:
  media:
  frontend_static:

services:
  pg:
    container_name: pg
    image: pgvector/pgvector:0.8.3-pg18-trixie
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql
    restart: on-failure

  redis:
    image: redis:8.6-alpine
    container_name: redis
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data

  nginx:
    env_file: .env
    container_name: nginx
    build:
      context: nginx/
      dockerfile: Dockerfile
    depends_on:
      - app
      - frontend
    volumes:
      - static:/backend_static
      - frontend_static:/frontend_static
      - media:/backend_media
    ports:
      - "127.0.0.1:8000:80"
    restart: on-failure

  app:
    container_name: app
    build: backend
    env_file: .env
    depends_on:
      - pg
      - redis
    volumes:
      - media:/backend_media
      - static:/backend_static
    command: ["bash", "ex.sh"]

  worker:
    container_name: worker
    build: backend
    env_file: .env
    depends_on:
      - pg
      - redis
    volumes:
      - media:/backend_media
    command: uv run celery -A service worker -l INFO

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    volumes:
      - frontend_static:/frontend_static
