# Generated by Django 6.0.6 on 2026-06-29 08:18

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    operations = [VectorExtension()]
