# Generated by Django 6.0.6 on 2026-06-29 08:21

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='estimates/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('done', 'Готов'), ('error', 'Ошибка')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('column_mapping', models.JSONField(default=dict)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('parsed_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('row_errors', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='price_lists/%Y/%m/')),
                ('column_mapping', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Ожидает обработки'), ('processing', 'Обрабатывается'), ('done', 'Готов'), ('error', 'Ошибка')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('parsed_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('row_errors', models.JSONField(default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.CharField(db_index=True, max_length=128)),
                ('name', models.CharField(db_index=True, max_length=512)),
                ('unit', models.CharField(max_length=128)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=256, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('inn', models.CharField(blank=True, db_index=True, max_length=12)),
                ('currency', models.CharField(choices=[('RUB', 'Rub'), ('USD', 'Usd'), ('EUR', 'Eur'), ('CNY', 'Cny')], default='RUB', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_status', models.CharField(choices=[('unmatched', 'Не сопоставлено'), ('matched', 'Сопоставлено'), ('no_match', 'Без соответствия')], default='unmatched', max_length=20)),
                ('match_confidence', models.FloatField(blank=True, null=True)),
                ('match_comment', models.TextField(blank=True)),
                ('article', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=512)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('row_number', models.PositiveIntegerField(default=0)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.pricelist')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_list_items', to='app.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_status', models.CharField(choices=[('unmatched', 'Не сопоставлено'), ('matched', 'Сопоставлено'), ('no_match', 'Без соответствия')], default='unmatched', max_length=20)),
                ('match_confidence', models.FloatField(blank=True, null=True)),
                ('match_comment', models.TextField(blank=True)),
                ('name', models.CharField(max_length=512)),
                ('article', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('row_number', models.PositiveIntegerField(default=0)),
                ('prices', models.JSONField(default=dict)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.estimate')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_items', to='app.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app.productgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='app.productgroup'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimates', to='app.project'),
        ),
        migrations.AddField(
            model_name='pricelist',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='app.supplier'),
        ),
    ]
